{{- if .Values.jobs.migrateDb.enabled }}
{{- $nodeSelector := .Values.nodeSelector }}
{{- $tolerations := .Values.tolerations }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-migrations-job
  labels:
    tier: airflow
    component: migrate-db-job
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    {{- with .Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    "helm.sh/hook": pre-upgrade,pre-install
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
spec:  
  template:
    spec:
      serviceAccountName: {{ .Values.airflowKsa | default "airflow" }}
      nodeSelector:
{{ toYaml $nodeSelector | indent 8 }}
      tolerations:
{{ toYaml $tolerations | indent 8 }}
      initContainers:
      - name: wait-for-db-started
        image: busybox
        command: ['sh', '-c', "until nc -zv movement-db.{{ .Release.Namespace }}.svc.cluster.local {{ .Values.database.port }}; do echo waiting for mydb; sleep 2; done"]
      containers:
      - name: run-airflow-migrations
        image: {{ template "scheduler_image" . }}
        imagePullPolicy: {{ .Values.scheduler.image.pullPolicy | default .Values.image.pullPolicy | quote }}
        {{- if .Values.jobs.migrateDb.command }}
        command: {{ tpl (toYaml .Values.jobs.migrateDb.command) . | nindent 12 }}
        {{- end }}
        {{- if .Values.jobs.migrateDb.args }}
        args: {{ tpl (toYaml .Values.jobs.migrateDb.args) . | nindent 12 }}
        {{- end }} 
        env: []
        envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-env-config
        volumeMounts:
        {{- if .Values.airflowConfigFile }}
        - name: config
          mountPath: {{ template "airflow_config_path" . }}
          subPath: airflow.cfg
          readOnly: true
        {{- end }}
      volumes:
      {{- if .Values.airflowConfigFile }}
      - name: config
        configMap:
          name: {{ .Release.Name }}-config
      {{- end }}
      restartPolicy: Never
  backoffLimit: 1
{{- end }}