{{- $nodeSelector := .Values.nodeSelector }}
{{- $tolerations := .Values.tolerations }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-default-user-creation-job
  labels:
    tier: airflow
    component: default-user-creation-job
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    {{- with .Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
spec:  
  template:
    spec:
      serviceAccountName: {{ .Values.airflowKsa | default "airflow" }}
      nodeSelector:
{{ toYaml $nodeSelector | indent 8 }}
      tolerations:
{{ toYaml $tolerations | indent 8 }}
      initContainers:
      - name: wait-for-db-migrations
        image: {{ template "scheduler_image" . }}
        command: ["sh", "-c"]
        args:
          - until nc -zv movement-db.{{ .Release.Namespace }}.svc.cluster.local {{ .Values.database.port }}; do echo waiting for airflow db; sleep 2; done;
            airflow db check-migrations --migration-wait-timeout={{ .Values.jobs.migrateDb.waitTimeout }};
        envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-env-config
      containers:
      - name: default-user-creation-job
        image: {{ template "scheduler_image" . }}
        imagePullPolicy: {{ .Values.scheduler.image.pullPolicy | default .Values.image.pullPolicy | quote }}
        command: ["sh", "-c"]
        args:
          - airflow users create --username admin --password admin --firstname Service --lastname Data --role Admin --email data-services@mservice.com.vn
        env: []
        envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-env-config
        volumeMounts:
        {{- if .Values.airflowConfigFile }}
        - name: config
          mountPath: {{ template "airflow_config_path" . }}
          subPath: airflow.cfg
          readOnly: true
        {{- end }}
      volumes:
      {{- if .Values.airflowConfigFile }}
      - name: config
        configMap:
          name: {{ .Release.Name }}-config
      {{- end }}
      restartPolicy: Never
  backoffLimit: 1