{{- $nodeSelector := .Values.nodeSelector }}
{{- $tolerations := .Values.tolerations }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: restart-docs-worker
  namespace: {{ .Release.Namespace }}
  labels:
    tier: datalake
    service: movement
    component: grist-cronjob
    worker: docs
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    {{- with .Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  schedule: "0 0 * * *"  # Run at midnight every day
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ .Values.gristKsa | default "grist-ksa" }}
          nodeSelector:
{{ toYaml $nodeSelector | indent 12 }}
          tolerations:
{{ toYaml $tolerations | indent 12 }}
          restartPolicy: OnFailure
          containers:
          - name: kubectl
            image: bitnami/kubectl:latest
            command:
            - /bin/sh
            - -c
            - kubectl delete pod -l worker=docs -l service=movement -l component=grist --force --grace-period=0