apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config-env
  labels:
    tier: datalake
    service: movement
    component: config
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
{{- with .Values.labels }}
{{ toYaml . | indent 4 }}
{{- end -}}
{{- $Global := . }} # prevent error converting YAML to JSON: yaml: line 14: mapping values are not allowed in this context
data:
  TYPEORM_TYPE: postgres
  TYPEORM_DATABASE: grist
  TYPEORM_USERNAME: grist
  TYPEORM_PASSWORD: grist
  TYPEORM_HOST: postgres.db-service.svc.cluster.local
  TYPEORM_PORT: "5432"
  GRIST_SESSION_SECRET: vinhdp
  GRIST_MANAGED_WORKERS: "true"
  # GRIST_SUPPORT_EMAIL: data-services@mservice.com.vn
  # GRIST_DEFAULT_EMAIL: data-services@mservice.com.vn
  APP_HOME_URL: https://{{ .Values.grist.host }}
  APP_HOME_INTERNAL_URL: http://{{ .Release.Name }}-home.pulse.svc.cluster.local:{{ .Values.grist.port }}
  APP_DOC_URL: https://{{ .Values.grist.host }}
  APP_DOC_INTERNAL_URL: http://{{ .Release.Name }}-docs.pulse.svc.cluster.local:{{ .Values.grist.port }}
  GRIST_OIDC_IDP_ISSUER: https://accounts.google.com
  GRIST_OIDC_IDP_SCOPES: "openid email profile"
  GRIST_OIDC_IDP_SKIP_END_SESSION_ENDPOINT: "true"
  GRIST_FORCE_LOGIN: "true"
  GRIST_UI_FEATURES: createSite,multiSite,multiAccounts,sendToDrive
  GRIST_SANDBOX_FLAVOR: gvisor
  REDIS_URL: redis://redis.db-service.svc.cluster.local/2
  GRIST_TELEMETRY_LEVEL: full
  GRIST_PROMCLIENT_PORT: "9091"

