kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}
  labels:
    tier: datalake
    service: movement
    component: database
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
{{- with .Values.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: ClusterIP
  selector:
    tier: datalake
    service: movement
    component: database
    release: {{ .Release.Name }}
  ports:
    - name: database
      protocol: TCP
      port: {{ .Values.database.port }}
      targetPort: {{ .Values.database.port }}
