apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    tier: datalake
    service: movement
    component: postgrest
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
{{- with .Values.labels }}
{{ toYaml . | indent 4 }}
{{- end -}}
{{- $Global := . }} # prevent error converting YAML to JSON: yaml: line 14: mapping values are not allowed in this context
data:
  postgrest.conf: {{ (tpl (.Files.Get "files/postgrest.conf") . | quote ) }}
