{{- $nodeSelector := or .Values.postgrest.nodeSelector .Values.nodeSelector }}
{{- $tolerations := or .Values.postgrest.tolerations .Values.tolerations }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}
  labels:
    tier: datalake
    service: movement
    component: postgrest
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
{{- with .Values.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: datalake
      service: movement
      component: postgrest
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        tier: datalake
        service: movement
        component: postgrest
        release: {{ .Release.Name }}
{{- with .Values.labels }}
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
      serviceAccountName: {{ .Values.airflowKsa | default "airflow" }}
      nodeSelector:
{{ toYaml $nodeSelector | indent 8 }}
      tolerations:
{{ toYaml $tolerations | indent 8 }}
      restartPolicy: Always
      imagePullSecrets:
        - name: {{ .Values.registry.secretName }}
      containers:
        - name: postgrest
          image: {{ template "postgrest_image" . }}
          imagePullPolicy: {{ .Values.postgrest.pullPolicy }}
          ports:
            - containerPort: {{ .Values.postgrest.port }}
          args: {{ .Values.postgrest.args | toJson }}
          env:
          - name: PGRST_LOG_LEVEL
            value: {{ .Values.postgrest.logLevel }}
          volumeMounts:
          - name: config
            mountPath: {{ template "postgrest_config_path" . }}
            subPath: postgrest.conf
            readOnly: true
      volumes:
      - name: config
        configMap:
          name: {{ .Release.Name }}-config


