apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: forward-http-request-to-sep # this service will be created in Cloud Run via Skaffold
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/minScale: 1
    run.googleapis.com/function-target: forward_http_request_to_sep
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      labels:
        run.googleapis.com/startupProbeType: Default
      annotations:
        autoscaling.knative.dev/maxScale: '2'
        autoscaling.knative.dev/minScale: '1'
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/vpc-access-connector: google-chat-vpc-connector
        run.googleapis.com/vpc-access-egress: private-ranges-only
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containers:
      - image: us-docker.pkg.dev/data-platform-exp-322803/gcr.io/cloudfunctions
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: FUNCTION_SIGNATURE_TYPE
          value: http
        - name: FUNCTION_SOURCE
          value: app/main.py
        resources:
          limits:
            cpu: '1'
            memory: 512Mi
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 8080
  traffic:
  - percent: 100
    latestRevision: true