tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "service"
    effect: "NoSchedule"

nodeSelector:
  cloud.google.com/gke-nodepool: spot-e2-2-8

gristKsa: pulse-ksa

database:
  host: postgres.db-service.svc.cluster.local
  port: 5432
  dbname: grist

grist:
  enabled: true

  port: 8484
  host: pulse.mservice.io

  workerReplica: 1

  pv:
    diskId: projects/momovn-data-platform/zones/us-central1-c/disks/pulse-ssd-pd
    storageClass: standard-rwo
  pvc:
    storageSize: 20Gi

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                  - us-central1-c
  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 4Gi
