services:
  bot-anathema:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot-anathema
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "8000"
    networks:
      - default-network

networks:
  default-network:
    name: default-network
    external: true