services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"   # Map host port 80 to container port 80 (for HTTP redirect)
      - "443:443" # Map host port 443 to container port 443 (for HTTPS)
    volumes:
      # Mount your custom Nginx configuration file
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # Mount Certbot SSL certificates from your host
      - /etc/letsencrypt:/etc/letsencrypt:ro
      # Mount Nginx logs directory (optional, but good for debugging)
      # - ./nginx/logs:/var/log/nginx
    networks:
      - default-network

networks:
  default-network:
    name: default-network
    external: true
    driver: bridge