apiVersion: skaffold/v4beta12
kind: Config
profiles:
  - name: general-purpose
    build:
      artifacts:
        - image: vudangquynhgiang/general-purpose
          context: ./images
          docker:
            dockerfile: dockerfiles/Dockerfile
      local:
        push: true
      tagPolicy:
        sha256: {}
    deploy: {}