labels: {}

registry:
  secretName: docker-pull-key

database:
  enabled: true

  image:
    repository: postgres
    tag: "16.3"

  port: 5432

  pv:
    diskId: projects/data-platform-exp-322803/zones/us-central1-c/disks/movement-database-pd
    storageClass: standard-rwo
  pvc:
    storageSize: 10Gi

jobs:
  setupDb:
    enabled: true
    waitTimeout: 300