---
apiVersion: skaffold/v4beta2
kind: Config
profiles:
- name: dev
  build:
    artifacts:
    - image: docker.mservice.io/momovn-dev/gke/mekong/movement-cdc
      context: .
      bazel:
        target: //mekong/movement/python/services:change_data_capture_consumer_deploy.tar
    local:
      push: true

  deploy:
    helm:
      releases:
      - name: movement-cdc
        chartPath: mekong/movement/helm-deploy/movement-cdc
        namespace: mekong
        valuesFiles:
        - mekong/movement/helm-deploy/movement-cdc/values-dev.yaml

- name: prod
  build:
    artifacts:
    - image: docker.mservice.io/momovn-dev/gke/mekong/movement-cdc
      context: .
      bazel:
        target: //mekong/movement/python/services:change_data_capture_consumer_deploy.tar
    local:
      push: true

  deploy:
    helm:
      releases:
      - name: movement-cdc
        chartPath: mekong/movement/helm-deploy/movement-cdc
        namespace: mekong
        valuesFiles:
        - mekong/movement/helm-deploy/movement-cdc/values-prod.yaml

