{{- $nodeSelector := or .Values.webserver.nodeSelector .Values.nodeSelector }}
{{- $tolerations := or .Values.webserver.tolerations .Values.tolerations }}
---
apiVersion: v1
kind: Pod
metadata:
  name: will-always-be-set-dynamically-at-pod-launch
spec:
  serviceAccountName: {{ .Values.airflowKsa | default "airflow" }}
  nodeSelector:
{{ toYaml $nodeSelector | indent 4 }}
  tolerations:
{{ toYaml $tolerations | indent 4 }}
  containers:
  - name: base
    image: {{ template "airflow_image" . }}
    imagePullPolicy: {{ .Values.scheduler.image.pullPolicy | default .Values.image.pullPolicy | quote }}
    env: []
    envFrom:
    - configMapRef:
        name: {{ .Release.Name }}-env-config
    volumeMounts:
    {{- if .Values.airflowConfigFile }}
    - name: config
      mountPath: {{ template "airflow_config_path" . }}
      subPath: airflow.cfg
      readOnly: true
    {{- end }}
    resources:
      limits:
        cpu: 150m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
  restartPolicy: Never
  volumes:
  {{- if .Values.airflowConfigFile }}
  - name: config
    configMap:
      name: {{ .Release.Name }}-config
  {{- end }}
