apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    tier: datalake
    component: config
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
{{- with .Values.labels }}
{{ toYaml . | indent 4 }}
{{- end -}}
{{- $Global := . }} # prevent error converting YAML to JSON: yaml: line 14: mapping values are not allowed in this context
data:
{{- if .Values.airflowConfigFile }}
  airflow.cfg: {{ (tpl (.Files.Get .Values.airflowConfigFile) . | quote ) }}
{{- end }}
  webserver_config.py: {{ (tpl (.Files.Get "files/webserver_config.py") . | quote ) }}
  kubernetes-pod-template-file.yaml: {{ (tpl (.Files.Get "files/kubernetes-pod-template-file.yaml") . | quote ) }}

