services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
      # platform: [linux/amd64]
      # no_cache: true
    # image: vudangquynhgiang/telegram-bot
    container_name: telegram-bot
    ports:
      - "443:8000"
    command: ["fastapi", "run", "app/main.py"]