services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
      # platform: [linux/amd64]
      # no_cache: true
    # image: vudangquynhgiang/telegram-bot
    container_name: telegram-bot
    ports:
      - "443:8000"
    command: ["fastapi", "run", "app/main.py"]

  nginx:
    image: nginx:latest # Use the official Nginx image
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"   # Map host port 80 to container port 80 (for HTTP redirect)
      - "443:443" # Map host port 443 to container port 443 (for HTTPS)
    volumes:
      # Mount your custom Nginx configuration file
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # Mount Certbot SSL certificates from your host
      # This path must match where Certbot saved your certs on the host machine!
      - /etc/letsencrypt/live/quynhgiang.info/:/etc/nginx/certs/:ro
      # Mount Nginx logs directory (optional, but good for debugging)
      - ./nginx/logs:/var/log/nginx
    # Ensure Nginx starts after the FastAPI app is ready (though Nginx retries connections)
    depends_on:
      - telegram-bot
    networks:
      - app-network # Use a custom network for better isolation and naming

networks:
  app-network:
    driver: bridge